DROP TABLE students;
DROP TABLE houses;


CREATE TABLE houses(
id SERIAL4 PRIMARY KEY,
name VARCHAR(255)
);

CREATE TABLE students(
  id SERIAL4 PRIMARY KEY,
  name VARCHAR(255),
  house INT4 REFERENCES houses(id) ON DELETE CASCADE,
  age INT2
);
